In [2]:
import numpy as np

x = [0,1,2,3,4,5]
x

[0, 1, 2, 3, 4, 5]

In [3]:
y = np.array(x)
y = y.reshape([2,3])

In [4]:
y[0,0]

0

In [5]:
y = np.array(range(100)).reshape([10,10])
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
y [[0,2,4,6,8], :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [28]:
y[:,:] % 2 == 0

array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

In [7]:
y[:,[0,2,4,6,8]]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [8]:
y % 2 == 0


array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

# Jupyter notes

A jupyter notebook is a way to use python interactively
* it consists of "cells"
* Each cell starts with a special set of characters
* Cells that start with '#%% md' indicate a cell that has markdown language in it.
* Cells that start with '#%%' have code in them.
* here's a link to a cheat sheet for Markdown:
* https://www.datacamp.com/community/tutorials/markdown-in-jupyter-notebook

In [9]:
# this is a code block, it it ends with a value, the value will be printed in the output
5 + 5

10

In [10]:
# numpy is a library of tools used for dealing with data.  Lots of stuff is based on numpy and
# being able to use it well is very powerful.
# you access numpy by importing it into your project, normally like this:

import numpy as np
# data mostly comes in matrices.  a matrix is an array of numbers:

In [11]:
# the range(end) function makes a list from zero until (but not including) the end.
range(10)

range(0, 10)

In [12]:
ar = np.array(range(10))

In [13]:
# You can access elements from an array just like you do  in javascript:
ar[4]

4

In [14]:
# specifying an array as the index will grab each element of the array:
ar[[1, 3, 5, 7, 9]]

array([1, 3, 5, 7, 9])

In [15]:
# the colon 'a:b' operator means "from a until b"  i.e. 0:3 means [0,1,2]
# you can also "slice" a chunk out
ar[3:8]

array([3, 4, 5, 6, 7])

In [16]:
# arrays of data can have 1, 2 or more dimensions:
m = np.array(range(16)).reshape([4, 4])
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
# two dimensional arrays can be accessed in two ways:
print(f"m[2,2] {m[2, 2]} is the same as m[2][2] {m[2][2]}")

m[2,2] 10 is the same as m[2][2] 10


In [18]:
# you can use the colon to slice out rows:
m[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# you can also slice columns out.  a ':' by itself means all rows or columns depending on where it is.  The
# example below the first : means "every column"
m[:, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [20]:
# or both
m[0:3, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [21]:
# this will also slice out specific rows, this gives row 0 and row 2
m[[0, 2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [22]:
# you can also slice out specific rows
m[[True, False, True, False]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [23]:
# this is kind of fancy but it compares the 0 column in each row to 4, any which are greater than four
# result in true, the others are false.
m[:, 0] > 4

array([False, False,  True,  True])

In [24]:
# this
m[m[:, 0] > 4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
m[m[:, 0] / 4 == 3]

array([[12, 13, 14, 15]])