# Jupyter notes

A jupyter notebook is a way to use python interactively
* it consists of "cells"
* Each cell starts with a special set of characters
* Cells that start with '#%% md' indicate a cell that has markdown language in it.
* Cells that start with '#%%' have code in them.
* here's a link to a cheat sheet for Markdown:
* https://www.datacamp.com/community/tutorials/markdown-in-jupyter-notebook

In [70]:
# this is a code block, it it ends with a value, the value will be printed in the output
5 + 5

10

In [71]:
# numpy is a library of tools used for dealing with data.  Lots of stuff is based on numpy and
# being able to use it well is very powerful.
# you access numpy by importing it into your project, normally like this:

import numpy as np
# data mostly comes in matrices.  a matrix is an array of numbers:

In [72]:
# the range(end) function makes a list from zero until (but not including) the end.
range(10)

range(0, 10)

In [73]:
ar = np.array(range(10))

In [74]:
# You can access elements from an array just like you do  in javascript:
ar[4]

4

In [75]:
# specifying an array as the index will grab each element of the array:
ar[[1, 3, 5, 7, 9]]

array([1, 3, 5, 7, 9])

In [76]:
# the colon 'a:b' operator means "from a until b"  i.e. 0:3 means [0,1,2]
# you can also "slice" a chunk out
ar[3:8]

array([3, 4, 5, 6, 7])

In [77]:
# arrays of data can have 1, 2 or more dimensions:
m = np.array(range(16)).reshape([4, 4])
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
# two dimensional arrays can be accessed in two ways:
print(f"m[2,2] {m[2, 2]} is the same as m[2][2] {m[2][2]}")

m[2,2] 10 is the same as m[2][2] 10


In [79]:
# you can use the colon to slice out rows:
m[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
# you can also slice columns out.  a ':' by itself means all rows or columns depending on where it is.  The
# example below the first : means "every column"
m[:, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [81]:
# or both
m[0:3, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [82]:
# this will also slice out specific rows, this gives row 0 and row 2
m[[0, 2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [83]:
# you can also slice out specific rows
m[[True, False, True, False]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [84]:
# this is kind of fancy but it compares the 0 column in each row to 4, any which are greater than four
# result in true, the others are false.
m[:, 0] > 4

array([False, False,  True,  True])

In [85]:
# this
m[m[:, 0] > 4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
m[m[:, 0] / 4 == 3]

array([[12, 13, 14, 15]])